name: Update GitHub Profile Stats
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: y471n
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 2%
          plugin_stars: yes
          plugin_contributions: yes
          plugin_repositories: yes
          plugin_isocalendar: yes # Streak calendar
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes # GitHub achievements
          plugin_followup: yes # Recent interactions
          plugin_people: yes # People you follow

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add github-metrics.svg metrics.plugin.*
          git commit -m "Updated GitHub profile stats" || exit 0
          git push
